# Generated by Django 5.2.16 on 2026-07-17 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key', models.CharField(editable=False, max_length=15, unique=True)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('days_remaining', models.IntegerField(default=0)),
                ('last_topup_bundle_type', models.CharField(blank=True, choices=[('custom', 'Custom amount'), ('30day', '30-day bundle'), ('60day', '60-day bundle'), ('100day', '100-day bundle'), ('300day', '300-day bundle'), ('1000day', '1000-day bundle')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_checkin_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle_type', models.CharField(choices=[('custom', 'Custom amount'), ('30day', '30-day bundle'), ('60day', '60-day bundle'), ('100day', '100-day bundle'), ('300day', '300-day bundle'), ('1000day', '1000-day bundle')], max_length=10)),
                ('days_added', models.IntegerField()),
                ('amount_paid_pesos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='machines.machine')),
            ],
        ),
    ]
