# Generated by Django 5.2.16 on 2026-07-20 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle_type', models.CharField(choices=[('custom', 'Custom amount'), ('30day', '30-day bundle'), ('60day', '60-day bundle'), ('100day', '100-day bundle'), ('300day', '300-day bundle'), ('1000day', '1000-day bundle')], max_length=10)),
                ('days', models.IntegerField()),
                ('amount_pesos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paymongo_checkout_session_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='machines.machine')),
            ],
        ),
    ]
