# Generated by Django 5.2.16 on 2026-07-24 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0005_license_account_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='generated_by',
            field=models.ForeignKey(blank=True, editable=False, help_text="Who actually clicked 'Generate License Key.' Set once at creation, never changed afterward -- distinct from `account`, which tracks who later claimed the key on a Machine and may be a different person entirely. SET_NULL (not CASCADE) so deleting an Account doesn't erase the historical fact that a license was generated -- only who generated it becomes unknown.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_licenses', to=settings.AUTH_USER_MODEL),
        ),
    ]
