# Generated by Django 5.2.16 on 2026-07-27 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0006_license_generated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronJobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=100, unique=True)),
                ('last_run_date', models.DateField()),
            ],
        ),
    ]
