# Generated by Django 5.2.16 on 2026-07-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0007_cronjobrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='recovery_password_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='license',
            name='release_failed_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='license',
            name='release_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
