# Generated by Django 5.2.16 on 2026-07-28 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0008_license_recovery_machine_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='zero_balance_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
