# Generated by Django 5.2.16 on 2026-08-02 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0009_machine_zero_balance_since'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
