# Generated by Django 5.2.16 on 2026-08-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0010_license_activated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='license_points',
            field=models.PositiveIntegerField(default=0, help_text='End Goals #14/#17: points inserted specifically into this license (separate from Account.balance_points, the general wallet, and Machine.days_remaining, which funds basic day-to-day operation). Zero means the box enforces the 2-user concurrent cap; any positive value unlocks unlimited concurrent access.'),
        ),
    ]
