# Generated by Django 5.2.16 on 2026-07-20 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='failed_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
