"""
Django settings for barathrum_backend project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Falls back to the original dev-only key so `manage.py runserver` keeps working locally with no
# environment variables set. Railway MUST have a real SECRET_KEY set in its Variables tab —
# see the deployment report for the exact value to generate/set.
SECRET_KEY = os.environ.get(
    'SECRET_KEY', 'django-insecure-r(ev&oy(4b^$3dzoc2r(hrhhsljr=atpcnyy@j+4mgp=6rk!ae'
)

# SECURITY WARNING: don't run with debug turned on in production!
#
# Careful parsing note: os.environ.get() returns a *string*, and bool("False") is True in
# Python (any non-empty string is truthy). Naively doing `bool(os.environ.get('DEBUG', True))`
# would leave production in DEBUG=True the moment DEBUG=False is set as a literal string, which
# is exactly backwards from what we want. We explicitly compare against a known "truthy string"
# set instead, and default to 'True' only for local dev (i.e. only when the env var is entirely
# absent, e.g. running `manage.py runserver` on a laptop) — if DEBUG is set to anything in the
# environment, it must be one of these exact strings to be treated as True.
DEBUG = os.environ.get('DEBUG', 'True').strip().lower() in ('true', '1', 'yes', 'on')

# Comma-separated list from env (e.g. "barathrum.up.railway.app,barathrum.example.com"), plus
# localhost/127.0.0.1/testserver kept for local dev and the Django test client regardless of env.
_env_allowed_hosts = [
    h.strip() for h in os.environ.get('ALLOWED_HOSTS', '').split(',') if h.strip()
]
ALLOWED_HOSTS = list({'localhost', '127.0.0.1', 'testserver', *_env_allowed_hosts})

# Comma-separated list from env (e.g. "https://barathrum.example.com"), with the current Railway
# domain as a safe fallback so this doesn't need a Variable set just to keep working today.
# CSRF_TRUSTED_ORIGINS entries must include the scheme (https://) — that's a Django requirement,
# unlike ALLOWED_HOSTS above which is bare hostnames only.
_env_csrf_trusted_origins = [
    o.strip() for o in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()
]
CSRF_TRUSTED_ORIGINS = list({
    'https://barathrum-backend-production.up.railway.app',
    *_env_csrf_trusted_origins,
})

# Railway's proxy terminates HTTPS and forwards to the app over plain HTTP internally, adding an
# X-Forwarded-Proto header with the original scheme. Without this, Django sees every request as
# plain HTTP and incorrectly rejects CSRF-protected POSTs (e.g. /admin/ login) that actually came
# in over HTTPS. Safe locally too: `manage.py runserver` doesn't send this header, so local dev
# is unaffected either way.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'machines',
    'dashboard',
]

AUTH_USER_MODEL = 'accounts.Account'
LOGIN_URL = '/login/'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'barathrum_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'barathrum_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# Railway auto-provides DATABASE_URL once a Postgres add-on is attached — nothing to set manually
# for that one. Falls back to the original SQLite config when DATABASE_URL is absent, so local
# dev (`manage.py runserver` with no env vars) is completely unchanged from STEP 2.1/2.2.

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Whitenoise serves static files directly from the app process in production (Railway has no
# separate static-file server/CDN wired up). CompressedManifestStaticFilesStorage adds
# content-hashed filenames + gzip/brotli compression so browsers can cache aggressively.
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
